// just remove-from-bundle
require([
    '../lib/core',
    '../lib/access',
    '../lib/prop',
    '../lib/check',
    '../lib/is',
    '../lib/defaults',
    '../lib/from',
    '../lib/defineProperties',
    '../lib/defProps',
    '../lib/defineProperty',
    '../lib/defProp',
    '../lib/eachProperty',
    '../lib/eachProp',
    '../lib/isEmptyObject',
    '../lib/emptyObj',
    '../lib/stringToJSON',
    '../lib/toJSON',
    '../lib/toObjectLiteral',
    '../lib/toObj'
]);
