require([
    '../lib/access',
    '../lib/check',
    '../lib/is',
    '../lib/defaults',
    '../lib/defineProperties',
    '../lib/defProps',
    '../lib/defineProperty',
    '../lib/defProp',
    '../lib/eachProperty',
    '../lib/isEmptyObject',
    '../lib/parseUrl',
    '../lib/stringToJSON',
    '../lib/toObjectLiteral'
]);
