define([
    '../lib/access',
    '../lib/check',
    '../lib/ClassList',
    '../lib/defaults',
    '../lib/Define',
    '../lib/defineProperties',
    '../lib/defineProperty',
    '../lib/eachProperty',
    '../lib/findElements',
    '../lib/getPressedKey',
    '../lib/getRemoteParent',
    '../lib/isEmptyObject',
    '../lib/isTouchSupported',
    '../lib/isWindow',
    '../lib/loadElement',
    '../lib/LocalStorage',
    '../lib/addEventListener',
    '../lib/parseUrl',
    '../lib/stringToJSON',
    '../lib/toObjectLiteral'
], function (
    access,
    check,
    ClassList,
    defaults,
    Define,
    defineProperties,
    defineProperty,
    eachProperty,
    findElements,
    getPressedKey,
    getRemoteParent,
    isEmptyObject,
    isTouchSupported,
    isWindow,
    loadElement,
    LocalStorage,
    addEventListener,
    parseUrl,
    stringToJSON,
    toObjectLiteral
) {

    return {
        'access': access,
        'check': check,
        'ClassList': ClassList,
        'defaults': defaults,
        'Define': Define,
        'defineProperties': defineProperties,
        'defineProperty': defineProperty,
        'eachProperty': eachProperty,
        'findElements': findElements,
        'getPressedKey': getPressedKey,
        'getRemoteParent': getRemoteParent,
        'isEmptyObject': isEmptyObject,
        'isTouchSupported': isTouchSupported,
        'isWindow': isWindow,
        'loadElement': loadElement,
        'LocalStorage': LocalStorage,
        'addEventListener': addEventListener,
        'parseUrl': parseUrl,
        'stringToJSON': stringToJSON,
        'toObjectLiteral': toObjectLiteral
    };

});
